// Generated by CoffeeScript 2.5.1
(function() {
  /*1964js - JavaScript/HTML5 port of 1964 - N64 emulator
  Copyright (C) 2012 Joel Middendorf

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.*/
  var C1964jsVideoHLEle, root;

  C1964jsVideoHLEle = class C1964jsVideoHLEle extends C1964jsVideoHLE {
    loadMatrix(addr) {
      var a, i, j, k;
      //  todo: port and probably log warning message if true
      if (addr + 64 > this.core.currentRdramSize) {
        console.warn("loading matrix beyond ram size");
        return;
      }
      a = addr;
      k = 0;
      i = 0;
      const u8 = this.core.memory.u8;
      const u16 = this.core.memory.u16;
      const matToLoad = this.matToLoad;
      while (i < 4) {
        j = 0;
        while (j < 4) {
          // 0.0000152587890625 is 1.0/65536.0
          matToLoad[k] = ((u16[(a >>> 1) ^ 1] << 16 | u16[((a + 32) >>> 1) ^ 1]) >> 0) * 0.0000152587890625;
          matToLoad[k + 1] = ((u16[a >>> 1] << 16 | u16[(a + 32) >>> 1]) >> 0) * 0.0000152587890625;
          k += 2;
          a += 4;
          j += 2;
        }
        i += 1;
      }
    }

  };

  C1964jsVideoHLEle.prototype.getGbi0MoveWordOffset = function(pc) {
    return this.core.memory.u32[pc >> 2] >>> 8 & 0xffff;
  };

  C1964jsVideoHLEle.prototype.getGbi0MoveWordType = function(pc) {
    return this.core.memory.u8[pc];
  };

  C1964jsVideoHLEle.prototype.getGbi0MoveWordValue = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2];
  };

  //GBI0 Dlist struct
  C1964jsVideoHLEle.prototype.getGbi0DlistParam = function(pc) {
    //(@core.memory.u32[pc>>>2]) >>> 16 & 0x00ff
    return this.core.memory.u8[pc + 2];
  };

  C1964jsVideoHLEle.prototype.getGbi0DlistAddr = function(pc) { //this will probably be generic getGbi0Addr
    return this.core.memory.u32[(pc + 4) >>> 2];
  };

  C1964jsVideoHLEle.prototype.getCommand = function(pc) {
    return this.core.memory.u8[pc + 3];
  };

  //GBI0 Tri1 struct
  C1964jsVideoHLEle.prototype.getGbi0Tri1Flag = function(pc) {
    return this.core.memory.u8[pc + 7];
  };

  C1964jsVideoHLEle.prototype.getGbi0Tri1V0 = function(pc) {
    return this.core.memory.u8[pc + 6];
  };

  C1964jsVideoHLEle.prototype.getGbi0Tri1V1 = function(pc) {
    return this.core.memory.u8[pc + 5];
  };

  C1964jsVideoHLEle.prototype.getGbi0Tri1V2 = function(pc) {
    return this.core.memory.u8[pc + 4];
  };

  //GBI1 Tri2 struct
  C1964jsVideoHLEle.prototype.getGbi1Tri2V3 = function(pc) {
    return this.core.memory.u8[pc + 2];
  };

  C1964jsVideoHLEle.prototype.getGbi1Tri2V4 = function(pc) {
    return this.core.memory.u8[pc + 1];
  };

  C1964jsVideoHLEle.prototype.getGbi1Tri2V5 = function(pc) {
    return this.core.memory.u8[pc];
  };

  //GBI1 Line3D
  C1964jsVideoHLEle.prototype.getGbi1Line3dV0 = function(pc) {
    return this.core.memory.u8[pc + 6];
  };

  C1964jsVideoHLEle.prototype.getGbi1Line3dV1 = function(pc) {
    return this.core.memory.u8[pc + 5];
  };

  C1964jsVideoHLEle.prototype.getGbi1Line3dV2 = function(pc) {
    return this.core.memory.u8[pc + 4];
  };

  C1964jsVideoHLEle.prototype.getGbi1Line3dV3 = function(pc) {
    return this.core.memory.u8[pc + 7];
  };

  //GBI0 vertex struct
  C1964jsVideoHLEle.prototype.getGbi0NumVertices = function(pc) {
    //(@core.memory.u32[pc>>>2]) >>> 20 & 0x0F
    return (this.core.memory.u8[pc + 2] >> 4) & 0x0F;
  };

  C1964jsVideoHLEle.prototype.getGbi0Vertex0 = function(pc) {
    //(@core.memory.u32[pc>>>2]) >>> 16 & 0x0F
    return this.core.memory.u8[pc + 2] & 0x0F;
  };

  //GBI1 vertex struct
  C1964jsVideoHLEle.prototype.getGbi1NumVertices = function(pc) {
    return (this.core.memory.u8[pc + 1] >>> 2) & 0x3F;
  };

  C1964jsVideoHLEle.prototype.getGbi1Vertex0 = function(pc) {
    return (this.core.memory.u8[pc + 2] >>> 1) & 0x7F;
  };

  //Fiddled vertex struct - Legacy
  C1964jsVideoHLEle.prototype.getFiddledVertexX = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 16;
  };

  C1964jsVideoHLEle.prototype.getFiddledVertexY = function(pc) {
    return this.core.memory.u32[pc >>> 2] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getFiddledVertexZ = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 16;
  };

  //Vertex Struct
  C1964jsVideoHLEle.prototype.getVertexX = function(pc) {
    //if ((pc>>>0) > 0x00800000)
    //  alert "oops"
    return this.core.memory.u16[(pc >>> 1) ^ 1] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getVertexY = function(pc) {
    return this.core.memory.u16[pc >>> 1] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getVertexZ = function(pc) {
    return this.core.memory.u16[((pc + 4) >>> 1) ^ 1] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getVertexW = function(pc) {
    return this.core.memory.u16[(pc + 4) >>> 1] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getVertexS = function(pc) {
    return this.core.memory.u16[(pc + 10) >>> 1] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getVertexT = function(pc) {
    return this.core.memory.u16[(pc + 8) >>> 1] << 16 >> 16;
  };

  C1964jsVideoHLEle.prototype.getVertexColorR = function(pc) {
    return this.core.memory.u8[pc + 15];
  };

  C1964jsVideoHLEle.prototype.getVertexColorG = function(pc) {
    return this.core.memory.u8[pc + 14];
  };

  C1964jsVideoHLEle.prototype.getVertexColorB = function(pc) {
    return this.core.memory.u8[pc + 13];
  };

  C1964jsVideoHLEle.prototype.getVertexAlpha = function(pc) {
    return this.core.memory.u8[pc + 12];
  };

  C1964jsVideoHLEle.prototype.getVertexNormalX = function(pc) {
    return this.core.memory.u8[pc + 15] << 24 >> 24;
  };

  C1964jsVideoHLEle.prototype.getVertexNormalY = function(pc) {
    return this.core.memory.u8[pc + 14] << 24 >> 24;
  };

  C1964jsVideoHLEle.prototype.getVertexNormalZ = function(pc) {
    return this.core.memory.u8[pc + 13] << 24 >> 24;
  };

  C1964jsVideoHLEle.prototype.getVertexNormalA = function(pc) {
    return this.core.memory.u8[pc + 12] << 24 >> 24;
  };

  C1964jsVideoHLEle.prototype.getVertexLightX = function(pc) {
    return this.core.memory.u8[pc + 11] << 24 >> 24;
  };

  C1964jsVideoHLEle.prototype.getVertexLightY = function(pc) {
    return this.core.memory.u8[pc + 10] << 24 >> 24;
  };

  C1964jsVideoHLEle.prototype.getVertexLightZ = function(pc) {
    return this.core.memory.u8[pc + 9] << 24 >> 24;
  };

  //Texture Struct
  C1964jsVideoHLEle.prototype.getTextureLevel = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 11 & 7;
  };

  C1964jsVideoHLEle.prototype.getTextureTile = function(pc) {
    //(@core.memory.u32[pc>>>2]) >> 8 & 7
    return this.core.memory.u8[pc + 1] & 7;
  };

  C1964jsVideoHLEle.prototype.getTextureOn = function(pc) {
    //(@core.memory.u32[pc>>>2]) & 15
    return this.core.memory.u8[pc] & 15;
  };

  C1964jsVideoHLEle.prototype.getTextureScaleS = function(pc) {
    //(@core.memory.u32[(pc+4)>>>2]) >> 16 & 0xFFFF
    return this.core.memory.u16[(pc + 6) >>> 1];
  };

  C1964jsVideoHLEle.prototype.getTextureScaleT = function(pc) {
    //(@core.memory.u32[(pc+4)>>>2]) & 0xFFFF
    return this.core.memory.u16[(pc + 4) >>> 1];
  };

  //Combine Struct
  C1964jsVideoHLEle.prototype.getCombineLo = function(pc) {
    return this.core.memory.u32[pc >>> 2];
  };

  C1964jsVideoHLEle.prototype.getCombineHi = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2];
  };

  C1964jsVideoHLEle.prototype.getCombineA0 = function(pc) {
    return (this.core.memory.u32[pc >>> 2] >> 20) & 15;
  };

  C1964jsVideoHLEle.prototype.getCombineB0 = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 28) & 15;
  };

  C1964jsVideoHLEle.prototype.getCombineC0 = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 15 & 31;
  };

  C1964jsVideoHLEle.prototype.getCombineD0 = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 15) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineA0a = function(pc) {
    return (this.core.memory.u32[pc >>> 2] >> 12) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineB0a = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 12) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineC0a = function(pc) {
    return (this.core.memory.u32[pc >>> 2] >> 9) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineD0a = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 9) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineA1 = function(pc) {
    return (this.core.memory.u32[pc >>> 2] >> 5) & 15;
  };

  C1964jsVideoHLEle.prototype.getCombineB1 = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 24) & 15;
  };

  C1964jsVideoHLEle.prototype.getCombineC1 = function(pc) {
    return this.core.memory.u32[pc >>> 2] & 31;
  };

  C1964jsVideoHLEle.prototype.getCombineD1 = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 6) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineA1a = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 21) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineB1a = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 3) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineC1a = function(pc) {
    return (this.core.memory.u32[(pc + 4) >>> 2] >> 18) & 7;
  };

  C1964jsVideoHLEle.prototype.getCombineD1a = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] & 7;
  };

  //GBI0 matrix struct
  C1964jsVideoHLEle.prototype.gbi0isProjectionMatrix = function(pc) {
    if ((this.core.memory.u8[pc + 2] & 1) !== 0) {
      return true;
    } else {
      return false;
    }
  };

  C1964jsVideoHLEle.prototype.gbi0LoadMatrix = function(pc) {
    if ((this.core.memory.u8[pc + 2] & 2) !== 0) {
      return true;
    } else {
      return false;
    }
  };

  C1964jsVideoHLEle.prototype.gbi0PushMatrix = function(pc) {
    if ((this.core.memory.u8[pc + 2] & 4) !== 0) {
      return true;
    } else {
      return false;
    }
  };

  C1964jsVideoHLEle.prototype.gbi0PopMtxIsProjection = function(pc) {
    if ((this.core.memory.u8[pc + 4] & 1) !== 0) {
      return true;
    } else {
      return false;
    }
  };

  //TexRect struct
  //    uint32 dwXH    = (((gfx->words.w0)>>12)&0x0FFF)/4;
  // uint32 dwYH   = (((gfx->words.w0)    )&0x0FFF)/4;
  // uint32 tileno = ((gfx->words.w1)>>24)&0x07;
  // uint32 dwXL   = (((gfx->words.w1)>>12)&0x0FFF)/4;
  // uint32 dwYL   = (((gfx->words.w1)    )&0x0FFF)/4;
  // uint16 uS   = (uint16)(  dwCmd2>>16)&0xFFFF;
  // uint16 uT   = (uint16)(  dwCmd2    )&0xFFFF;
  // uint16  uDSDX   = (uint16)((  dwCmd3>>16)&0xFFFF);
  // uint16  uDTDY     = (uint16)((  dwCmd3    )&0xFFFF);
  //X coordinate of lower right
  C1964jsVideoHLEle.prototype.getTexRectXh = function(pc) {
    return this.core.memory.u32[pc >>> 2] >>> 12 & 0xFFF;
  };

  //Y coordinate of lower right
  C1964jsVideoHLEle.prototype.getTexRectYh = function(pc) {
    //(@core.memory.u32[pc>>>2]) & 0xFFF
    return this.core.memory.u16[pc >>> 1] & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getTexRectTileNo = function(pc) {
    //(@core.memory.u32[(pc+4)>>>2]) >>> 24 & 7
    return this.core.memory.u8[pc + 7] & 7;
  };

  //X coordinate of upper left
  C1964jsVideoHLEle.prototype.getTexRectXl = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >>> 12 & 0xFFF;
  };

  //Y coordinate of upper left
  C1964jsVideoHLEle.prototype.getTexRectYl = function(pc) {
    return this.core.memory.u16[(pc + 4) >>> 1] & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getTexRectS = function(pc) {
    return this.core.memory.u16[(pc + 14) >>> 1];
  };

  C1964jsVideoHLEle.prototype.getTexRectT = function(pc) {
    return this.core.memory.u16[(pc + 12) >>> 1];
  };

  C1964jsVideoHLEle.prototype.getTexRectDsDx = function(pc) {
    return this.core.memory.u32[(pc + 20) >>> 2] >>> 16 & 0xFFFF;
  };

  C1964jsVideoHLEle.prototype.getTexRectDtDy = function(pc) {
    return this.core.memory.u32[(pc + 20) >>> 2] & 0xFFFF;
  };

  //is this right?
  C1964jsVideoHLEle.prototype.getGbi1Type = function(pc) {
    return this.core.memory.u32[pc >>> 2] >>> 16 & 0xFF;
  };

  C1964jsVideoHLEle.prototype.getRspSegmentAddr = function(seg) {
    //TODO: May need to mask with rdram size - 1
    return (this.segments[(seg >> 24) & 0x0F] & 0xffffff) + (seg & 0xFFFFFF);
  };

  C1964jsVideoHLEle.prototype.getOtherModeL = function(pc) {
    return this.core.memory.u32[pc >>> 2];
  };

  C1964jsVideoHLEle.prototype.getOtherModeH = function(pc) {
    return this.core.memory.u32[pc >>> 2];
  };

  C1964jsVideoHLEle.prototype.getWord0 = function(pc) {
    return this.core.memory.u32[pc >>> 2];
  };

  C1964jsVideoHLEle.prototype.getWord1 = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2];
  };

  C1964jsVideoHLEle.prototype.getShort = function(pc) {
    return (this.core.memory.u8[pc ^ 3] << 24 | this.core.memory.u8[(pc + 1) ^ 3] << 16) >> 16;
  };

  
  //typedef struct {
  //    unsigned int    width:12;
  //    unsigned int    :7;
  //    unsigned int    siz:2;
  //    unsigned int    fmt:3;
  //    unsigned int    cmd:8;
  //    unsigned int    addr;
  //} GSetImg;

  C1964jsVideoHLEle.prototype.getTImgWidth = function(pc) {
    return this.core.memory.u32[pc >>> 2] & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getTImgSize = function(pc) {
    return this.core.memory.u32[pc >>> 2] >>> 19 & 3;
  };

  C1964jsVideoHLEle.prototype.getTImgFormat = function(pc) {
    return this.core.memory.u32[pc >>> 2] >>> 21 & 7;
  };

  C1964jsVideoHLEle.prototype.getTImgAddr = function(pc) {
    var tImgAddr;
    tImgAddr = this.core.memory.u32[(pc + 4) >>> 2];
    return this.getRspSegmentAddr(tImgAddr);
  };

  //SetTile
  C1964jsVideoHLEle.prototype.getSetTileFmt = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 21 & 7;
  };

  C1964jsVideoHLEle.prototype.getSetTileSiz = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 19 & 3;
  };

  C1964jsVideoHLEle.prototype.getSetTileLine = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 9 & 0x1FF;
  };

  C1964jsVideoHLEle.prototype.getSetTileTmem = function(pc) {
    return this.core.memory.u32[pc >>> 2] & 0x1FF;
  };

  C1964jsVideoHLEle.prototype.getSetTileTile = function(pc) {
    return this.core.memory.u8[(pc + 4) ^ 3] & 7;
  };

  C1964jsVideoHLEle.prototype.getSetTilePal = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 20 & 15;
  };

  C1964jsVideoHLEle.prototype.getSetTileCmt = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 18 & 3;
  };

  C1964jsVideoHLEle.prototype.getSetTileMirrorT = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 15 & 1;
  };

  C1964jsVideoHLEle.prototype.getSetTileMaskt = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 14 & 15;
  };

  C1964jsVideoHLEle.prototype.getSetTileShiftt = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 10 & 15;
  };

  C1964jsVideoHLEle.prototype.getSetTileCms = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 8 & 3;
  };

  C1964jsVideoHLEle.prototype.getSetTileMirrorS = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 5 & 1;
  };

  C1964jsVideoHLEle.prototype.getSetTileMasks = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 4 & 15;
  };

  C1964jsVideoHLEle.prototype.getSetTileShifts = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] & 15;
  };

  //LoadBlock
  C1964jsVideoHLEle.prototype.getLoadBlockTile = function(pc) {
    return this.core.memory.u8[(pc + 4) ^ 3] & 7;
  };

  C1964jsVideoHLEle.prototype.getLoadBlockUls = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 12 & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getLoadBlockUlt = function(pc) {
    return this.core.memory.u32[pc >>> 2] & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getLoadBlockLrs = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 12 & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getLoadBlockDxt = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] & 0xFFF;
  };

  //SetTileSize
  C1964jsVideoHLEle.prototype.getSetTileSizeTile = function(pc) {
    return this.core.memory.u8[(pc + 4) ^ 3] & 7;
  };

  C1964jsVideoHLEle.prototype.getSetTileSizeUls = function(pc) {
    return this.core.memory.u32[pc >>> 2] >> 12 & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getSetTileSizeUlt = function(pc) {
    return this.core.memory.u32[pc >>> 2] & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getSetTileSizeLrs = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] >> 12 & 0xFFF;
  };

  C1964jsVideoHLEle.prototype.getSetTileSizeLrt = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2] & 0xFFF;
  };

  //SetPrimColor
  C1964jsVideoHLEle.prototype.getSetPrimColorM = function(pc) {
    return this.core.memory.u32[pc >>> 2] >>> 8 & 0xFF;
  };

  C1964jsVideoHLEle.prototype.getSetPrimColorL = function(pc) {
    return this.core.memory.u32[pc >>> 2] & 0xFF;
  };

  C1964jsVideoHLEle.prototype.getSetPrimColorR = function(pc) {
    return this.core.memory.u8[pc + 7];
  };

  C1964jsVideoHLEle.prototype.getSetPrimColorG = function(pc) {
    return this.core.memory.u8[pc + 6];
  };

  C1964jsVideoHLEle.prototype.getSetPrimColorB = function(pc) {
    return this.core.memory.u8[pc + 5];
  };

  C1964jsVideoHLEle.prototype.getSetPrimColorA = function(pc) {
    return this.core.memory.u8[pc + 4];
  };

  //SetGeometryMode
  C1964jsVideoHLEle.prototype.getSetGeometryMode = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2];
  };

  C1964jsVideoHLEle.prototype.getClearGeometryMode = function(pc) {
    return this.core.memory.u32[(pc + 4) >>> 2];
  };

  C1964jsVideoHLEle.prototype.pow2roundup = function(value) {
    var result;
    result = 1;
    while (result < value) {
      result <<= 1;
    }
    return result;
  };

  //SetFillColor
  C1964jsVideoHLEle.prototype.getSetFillColorR = function(pc) {
    return this.core.memory.u8[pc + 7];
  };

  C1964jsVideoHLEle.prototype.getSetFillColorG = function(pc) {
    return this.core.memory.u8[pc + 6];
  };

  C1964jsVideoHLEle.prototype.getSetFillColorB = function(pc) {
    return this.core.memory.u8[pc + 5];
  };

  C1964jsVideoHLEle.prototype.getSetFillColorA = function(pc) {
    return this.core.memory.u8[pc + 4];
  };

  //setEnvColor
  C1964jsVideoHLEle.prototype.getSetEnvColorR = function(pc) {
    return this.core.memory.u8[pc + 7];
  };

  C1964jsVideoHLEle.prototype.getSetEnvColorG = function(pc) {
    return this.core.memory.u8[pc + 6];
  };

  C1964jsVideoHLEle.prototype.getSetEnvColorB = function(pc) {
    return this.core.memory.u8[pc + 5];
  };

  C1964jsVideoHLEle.prototype.getSetEnvColorA = function(pc) {
    return this.core.memory.u8[pc + 4];
  };

  //hack global space until we export classes properly
  //node.js uses exports; browser uses this (window)
  root = typeof exports !== "undefined" && exports !== null ? exports : self;

  root.C1964jsVideoHLEle = C1964jsVideoHLEle;

}).call(this);
