// Generated by CoffeeScript 2.5.1
(function() {
  /*1964js - JavaScript/HTML5 port of 1964 - N64 emulator
  Copyright (C) 2012 Joel Middendorf

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.*/
  //globals C1964jsEmulator
  "use strict";
  C1964jsEmulator.prototype.initOpcodeMap = function() {
    this.CPU_Instruction = [this.instr, this.REGIMM_instr, this.r4300i_j, this.r4300i_jal, this.r4300i_beq, this.r4300i_bne, this.r4300i_blez, this.r4300i_bgtz, this.r4300i_addi, this.r4300i_addiu, this.r4300i_slti, this.r4300i_sltiu, this.r4300i_andi, this.r4300i_ori, this.r4300i_xori, this.r4300i_lui, this.COP0_instr, this.COP1_instr, this.UNUSED, this.UNUSED, this.r4300i_beql, this.r4300i_bnel, this.r4300i_blezl, this.r4300i_bgtzl, this.r4300i_daddi, this.r4300i_daddiu, this.r4300i_ldl, this.r4300i_ldr, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_lb, this.r4300i_lh, this.r4300i_lwl, this.r4300i_lw, this.r4300i_lbu, this.r4300i_lhu, this.r4300i_lwr, this.r4300i_lwu, this.r4300i_sb, this.r4300i_sh, this.r4300i_swl, this.r4300i_sw, this.r4300i_sdl, this.r4300i_sdr, this.r4300i_swr, this.r4300i_cache, this.r4300i_ll, this.r4300i_lwc1, this.UNUSED, this.UNUSED, this.r4300i_lld, this.r4300i_ldc1, this.UNUSED, this.r4300i_ld, this.r4300i_sc, this.r4300i_swc1, this.UNUSED, this.UNUSED, this.r4300i_scd, this.r4300i_sdc1, this.UNUSED, this.r4300i_sd];
    this.r4300i_Instruction = [this.r4300i_sll, this.UNUSED, this.r4300i_srl, this.r4300i_sra, this.r4300i_sllv, this.UNUSED, this.r4300i_srlv, this.r4300i_srav, this.r4300i_jr, this.r4300i_jalr, this.UNUSED, this.UNUSED, this.r4300i_syscall, this.r4300i_break, this.UNUSED, this.r4300i_sync, this.r4300i_mfhi, this.r4300i_mthi, this.r4300i_mflo, this.r4300i_mtlo, this.r4300i_dsllv, this.UNUSED, this.r4300i_dsrlv, this.r4300i_dsrav, this.r4300i_mult, this.r4300i_multu, this.r4300i_div, this.r4300i_divu, this.r4300i_dmult, this.r4300i_dmultu, this.r4300i_ddiv, this.r4300i_ddivu, this.r4300i_add, this.r4300i_addu, this.r4300i_sub, this.r4300i_subu, this.r4300i_and, this.r4300i_or, this.r4300i_xor, this.r4300i_nor, this.UNUSED, this.UNUSED, this.r4300i_slt, this.r4300i_sltu, this.r4300i_dadd, this.r4300i_daddu, this.r4300i_dsub, this.r4300i_dsubu, this.r4300i_tge, this.r4300i_tgeu, this.r4300i_tlt, this.r4300i_tltu, this.r4300i_teq, this.UNUSED, this.r4300i_tne, this.UNUSED, this.r4300i_dsll, this.UNUSED, this.r4300i_dsrl, this.r4300i_dsra, this.r4300i_dsll32, this.UNUSED, this.r4300i_dsrl32, this.r4300i_dsra32];
    this.REGIMM_Instruction = [this.r4300i_bltz, this.r4300i_bgez, this.r4300i_bltzl, this.r4300i_bgezl, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_tgei, this.r4300i_tgeiu, this.r4300i_tlti, this.r4300i_tltiu, this.r4300i_teqi, this.UNUSED, this.r4300i_tnei, this.UNUSED, this.r4300i_bltzal, this.r4300i_bgezal, this.r4300i_bltzall, this.r4300i_bgezall, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
    this.COP0_Instruction = [this.r4300i_COP0_mfc0, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP0_mtc0, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.TLB_instr, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
    this.TLB_Instruction = [this.UNUSED, this.r4300i_COP0_tlbr, this.r4300i_COP0_tlbwi, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP0_tlbwr, this.UNUSED, this.r4300i_COP0_tlbp, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP0_eret, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
    this.COP1_Instruction = [this.r4300i_COP1_mfc1, this.r4300i_COP1_dmfc1, this.r4300i_COP1_cfc1, this.UNUSED, this.r4300i_COP1_mtc1, this.r4300i_COP1_dmtc1, this.r4300i_COP1_ctc1, this.UNUSED, this.COP1_BC_instr, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.COP1_S_instr, this.COP1_D_instr, this.UNUSED, this.UNUSED, this.COP1_W_instr, this.COP1_L_instr, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
    this.COP1_BC_Instruction = [this.r4300i_COP1_bc1f, this.r4300i_COP1_bc1t, this.r4300i_COP1_bc1fl, this.r4300i_COP1_bc1tl, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
    this.COP1_S_Instruction = [this.r4300i_COP1_add_s, this.r4300i_COP1_sub_s, this.r4300i_COP1_mul_s, this.r4300i_COP1_div_s, this.r4300i_COP1_sqrt_s, this.r4300i_COP1_abs_s, this.r4300i_COP1_mov_s, this.r4300i_COP1_neg_s, this.r4300i_COP1_roundl_s, this.r4300i_COP1_truncl_s, this.r4300i_COP1_ceill_s, this.r4300i_COP1_floorl_s, this.r4300i_COP1_roundw_s, this.r4300i_COP1_truncw_s, this.r4300i_COP1_ceilw_s, this.r4300i_COP1_floorw_s, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP1_cvtd_s, this.UNUSED, this.UNUSED, this.r4300i_COP1_cvtw_s, this.r4300i_COP1_cvtl_s, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_C_F_S, this.r4300i_C_UN_S, this.r4300i_C_EQ_S, this.r4300i_C_UEQ_S, this.r4300i_C_OLT_S, this.r4300i_C_ULT_S, this.r4300i_C_OLE_S, this.r4300i_C_ULE_S, this.r4300i_C_SF_S, this.r4300i_C_NGLE_S, this.r4300i_C_SEQ_S, this.r4300i_C_NGL_S, this.r4300i_C_LT_S, this.r4300i_C_NGE_S, this.r4300i_C_LE_S, this.r4300i_C_NGT_S];
    this.COP1_D_Instruction = [this.r4300i_COP1_add_d, this.r4300i_COP1_sub_d, this.r4300i_COP1_mul_d, this.r4300i_COP1_div_d, this.r4300i_COP1_sqrt_d, this.r4300i_COP1_abs_d, this.r4300i_COP1_mov_d, this.r4300i_COP1_neg_d, this.r4300i_COP1_roundl_d, this.r4300i_COP1_truncl_d, this.r4300i_COP1_ceill_d, this.r4300i_COP1_floorl_d, this.r4300i_COP1_roundw_d, this.r4300i_COP1_truncw_d, this.r4300i_COP1_ceilw_d, this.r4300i_COP1_floorw_d, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP1_cvts_d, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP1_cvtw_d, this.r4300i_COP1_cvtl_d, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_C_F_D, this.r4300i_C_UN_D, this.r4300i_C_EQ_D, this.r4300i_C_UEQ_D, this.r4300i_C_OLT_D, this.r4300i_C_ULT_D, this.r4300i_C_OLE_D, this.r4300i_C_ULE_D, this.r4300i_C_SF_D, this.r4300i_C_NGLE_D, this.r4300i_C_SEQ_D, this.r4300i_C_NGL_D, this.r4300i_C_LT_D, this.r4300i_C_NGE_D, this.r4300i_C_LE_D, this.r4300i_C_NGT_D];
    this.COP1_W_Instruction = [this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP1_cvts_w, this.r4300i_COP1_cvtd_w, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
    this.COP1_L_Instruction = [this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.r4300i_COP1_cvts_l, this.r4300i_COP1_cvtd_l, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED, this.UNUSED];
  };

  C1964jsEmulator.prototype.CPU_instruction = function(i, isDelay) {
    return this.CPU_Instruction[i >> 26 & 0x3f].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.instr = function(i, isDelay) {
    return this.r4300i_Instruction[this.helpers.fn(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.REGIMM_instr = function(i, isDelay) {
    return this.REGIMM_Instruction[this.helpers.rt(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP0_instr = function(i, isDelay) {
    return this.COP0_Instruction[this.helpers.rs(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP1_instr = function(i, isDelay) {
    return this.COP1_Instruction[this.helpers.rs(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.TLB_instr = function(i, isDelay) {
    return this.TLB_Instruction[this.helpers.fn(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP1_BC_instr = function(i, isDelay) {
    return this.COP1_BC_Instruction[this.helpers.rt(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP1_S_instr = function(i, isDelay) {
    return this.COP1_S_Instruction[this.helpers.fn(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP1_D_instr = function(i, isDelay) {
    return this.COP1_D_Instruction[this.helpers.fn(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP1_W_instr = function(i, isDelay) {
    return this.COP1_W_Instruction[this.helpers.fn(i)].call(this, i, isDelay);
  };

  C1964jsEmulator.prototype.COP1_L_instr = function(i, isDelay) {
    return this.COP1_L_Instruction[this.helpers.fn(i)].call(this, i, isDelay);
  };

}).call(this);
